version: 3.7
services:
  laravel:
    image: iamrgroot/laravel:${TAG:-php7.4fpm-node14}
    container_name: laravel
    user: ${UID}
    environment:
      TZ: ${TZ}
      CONTAINER_ROLE: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  laravel-scheduler:
    image: iamrgroot/laravel:${TAG:-php7.4fpm-node14}
    container_name: laravel-scheduler
    depends_on:
      - laravel
    user: ${UID}
    environment:
      TZ: ${TZ}
      CONTAINER_ROLE: scheduler
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  laravel-queue:
    image: iamrgroot/laravel:${TAG:-php7.4fpm-node14}
    container_name: laravel-queue
    depends_on:
      - laravel
    user: ${UID}
    environment:
      TZ: ${TZ}
      CONTAINER_ROLE: queue
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  
  laravel-db:
    image: mysql:latest
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: ${TZ}

  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${UID}
      - TZ=${TZ}
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/